version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_DeployAnywhereProject
  gitServerName: fr_stt_github
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
